#!/usr/bin/env node
'use strict';
// Stage 2 synthesis: parse the ts-stamped logs + <mgr>.json, classify install lines
// into canonical phase buckets, and emit a correlation matrix (phases x managers) to
// stdout and results/RESULTS.md. Pure regex over the logs -- no manual numbers.
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, 'results');
const ORDER = ['apk', 'pacman', 'dnf', 'apt', 'nix', 'brew'];

// Canonical install phases. Each install-log line is bucketed by the FIRST pattern it
// matches, in this order. Heuristic + cross-manager -> approximate by design.
const PHASES = [
  ['startup',   /read(ing)? (package |state |data)|loading|initiali|dnf5|apk-tools|^\s*[\d.]+\s+$|db|repositor/i],
  ['resolve',   /resolv|depend|prepar|transaction (check|test)|checking (keys|integrity|conflict|available|space)|conflict|Running transaction check/i],
  ['verify',    /verif|integrity|signature|openpgp|gpg|check.*integrity/i],
  ['unpack',    /unpack|installing|pouring|extract|upgrad|downgrad|copying path|inflat/i],
  ['configure', /setting up|scriptlet|processing triggers|post.?install|hook|sysusers|systemd|configur|certificate|template|update-|caveat|running/i],
  ['link',      /link|symlink|ldconfig|profile|generation|building profile/i],
];

// Best-effort dep-count / download-size extractors over the DOWNLOAD log text.
const DL_INFO = {
  apt:    (t) => ({ size: cap(t, /Need to get ([\d.]+ ?[kMG]i?B)/i), deps: count(t, /\bGet:\d+/g) }),
  apk:    (t) => ({ size: null,                                       deps: count(t, /Downloading /gi) }),
  dnf:    (t) => ({ size: cap(t, /Total (?:download )?size:\s*([\d.]+ ?[kMG]i?B)/i), deps: count(t, /\(\d+\/\d+\):/g) }),
  pacman: (t) => ({ size: cap(t, /Total Download Size:\s*([\d.]+ ?[kMG]i?B)/i), deps: cap(t, /Packages? \((\d+)\)/) }),
  nix:    (t) => ({ size: cap(t, /([\d.]+ ?[kMG]i?B) download/i),     deps: cap(t, /(\d+) paths? will be fetched/i) }),
  brew:   (t) => ({ size: null,                                       deps: count(t, /Downloading |Already downloaded/gi) }),
};

function cap(t, re) { const m = t.match(re); return m ? m[1] : null; }
function count(t, re) { const m = t.match(re); return m ? String(m.length) : null; }
function readLog(name, phase) {
  try { return fs.readFileSync(path.join(OUT, `${name}-${phase}.log`), 'utf8'); } catch { return ''; }
}
function parseTs(text) {
  return text.split('\n').map((l) => {
    const m = l.match(/^\s*([\d.]+)\s+(.*)$/);
    return m ? { d: parseFloat(m[1]), text: m[2] } : null;
  }).filter(Boolean);
}
function bucketize(lines) {
  const b = Object.fromEntries(PHASES.map(([k]) => [k, 0]));
  for (const { d, text } of lines) {
    const hit = PHASES.find(([, re]) => re.test(text));
    b[hit ? hit[0] : 'configure'] += d;
  }
  return b;
}
function topSteps(lines, n = 3) {
  return [...lines].sort((a, b) => b.d - a.d).slice(0, n)
    .map(({ d, text }) => `${d.toFixed(3)}s ${text.slice(0, 46).trim()}`);
}

// ---- collect ----
const rows = [];
for (const m of ORDER) {
  let meta;
  try { meta = JSON.parse(fs.readFileSync(path.join(OUT, `${m}.json`), 'utf8')); } catch { continue; }
  const installLines = parseTs(readLog(m, 'install'));
  const info = (DL_INFO[m] || (() => ({})))(readLog(m, 'download'));
  rows.push({
    ...meta,
    buckets: bucketize(installLines),
    installLogTotal: installLines.reduce((s, x) => s + x.d, 0),
    top: topSteps(installLines),
    size: info.size, deps: info.deps,
  });
}
if (!rows.length) { console.error('No results found in results/. Run `node run.js` first.'); process.exit(1); }

// ---- render ----
const cols = rows.map((r) => r.manager);
const pad = (s, w) => String(s).padEnd(w);
const num = (v) => (v == null ? '—' : Number(v).toFixed(2));

function matrix() {
  const label = (s) => pad(s, 20);
  const cell = (v) => pad(v, 9);
  const lines = [];
  lines.push(label('phase (seconds)') + cols.map((c) => cell(c)).join(''));
  lines.push('-'.repeat(20 + cols.length * 9));
  lines.push(label('download') + rows.map((r) => cell(num(r.download_s))).join(''));
  for (const [k] of PHASES)
    lines.push(label('  install:' + k) + rows.map((r) => cell(num(r.buckets[k]))).join(''));
  lines.push(label('install TOTAL') + rows.map((r) => cell(num(r.install_s))).join(''));
  lines.push('-'.repeat(20 + cols.length * 9));
  lines.push(label('git version') + rows.map((r) => cell(r.git)).join(''));
  lines.push(label('deps') + rows.map((r) => cell(r.deps ?? '—')).join(''));
  lines.push(label('download size') + rows.map((r) => cell(r.size ?? '—')).join(''));
  return lines.join('\n');
}

function md() {
  const head = `| phase (s) | ${cols.join(' | ')} |`;
  const sep = `|---|${cols.map(() => '---:').join('|')}|`;
  const row = (label, fn) => `| ${label} | ${rows.map(fn).join(' | ')} |`;
  const out = [
    '# Results — `git` install: phase correlation matrix', '',
    '_Generated by `synthesize.js` from the ts-stamped logs. Install sub-phases are a',
    'heuristic bucketing of log lines (see README) — totals (download / install) are the',
    'ground truth._', '',
    head, sep,
    row('**download**', (r) => num(r.download_s)),
    ...PHASES.map(([k]) => row('install: ' + k, (r) => num(r.buckets[k]))),
    row('**install TOTAL**', (r) => num(r.install_s)),
    row('git version', (r) => r.git),
    row('deps', (r) => r.deps ?? '—'),
    row('download size', (r) => r.size ?? '—'),
    '', '## Top install sub-steps (by measured delta)', '',
    ...rows.map((r) => `- **${r.manager}** (${r.image}): ` + r.top.map((s) => `\`${s}\``).join(' · ')),
    '',
  ];
  return out.join('\n');
}

console.log('\n' + matrix() + '\n');
console.log('Top install sub-steps:');
for (const r of rows) console.log(`  ${pad(r.manager, 8)} ${r.top.join('  |  ')}`);
fs.writeFileSync(path.join(OUT, 'RESULTS.md'), md());
console.log(`\nWrote ${path.join('results', 'RESULTS.md')}`);
